pipeline {
    agent any

    environment {
        AWS_ACCOUNT_ID = "740349584703"
        AWS_REGION = "ap-south-1"

        ECR_BACKEND = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/redbus-backend"
        ECR_FRONTEND = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/redbus-frontend"

        EC2_HOST = "13.207.1.215"
        EC2_USER = "ubuntu"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'YOUR_GITHUB_REPO_URL'
            }
        }

        stage('Build Docker Images') {
            steps {
                sh '''
                docker build -t backend ./backend
                docker build -t frontend ./frontend
                '''
            }
        }

        stage('Login to ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                '''
            }
        }

        stage('Tag & Push Images') {
            steps {
                sh '''
                docker tag backend:latest $ECR_BACKEND:latest
                docker tag frontend:latest $ECR_FRONTEND:latest

                docker push $ECR_BACKEND:latest
                docker push $ECR_FRONTEND:latest
                '''
            }
        }

        stage('Deploy to EC2') {
            steps {
                sh '''
                ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST "
                    aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 740349584703.dkr.ecr.ap-south-1.amazonaws.com

                    docker pull $ECR_BACKEND:latest
                    docker pull $ECR_FRONTEND:latest

                    docker stop backend || true
                    docker stop frontend || true

                    docker rm backend || true
                    docker rm frontend || true

                    docker run -d --name backend -p 5000:5000 $ECR_BACKEND:latest
                    docker run -d --name frontend -p 3000:3000 $ECR_FRONTEND:latest
                "
                '''
            }
        }
    }
}
