pipeline {
    agent any

    environment {
        AWS_ACCOUNT_ID = "740349584703"
        AWS_REGION = "ap-south-1"

        ECR_BACKEND = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/redbus-backend"
        ECR_FRONTEND = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/redbus-frontend"
    }

    stages {

        stage('Build Backend Image') {
            steps {
                sh 'docker build -t redbus-backend ./redbus-master/back-end-redbus'
            }
        }

        stage('Build Frontend Image') {
            steps {
                sh 'docker build -t redbus-frontend ./redbus-master/front-end-redbus'
            }
        }

        stage('Login to AWS ECR') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-cred'
                ]]) {

                    sh '''
                    aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 740349584703.dkr.ecr.ap-south-1.amazonaws.com
                    '''
                }
            }
        }

        stage('Tag Images') {
            steps {
                sh '''
                docker tag redbus-backend:latest $ECR_BACKEND:latest
                docker tag redbus-frontend:latest $ECR_FRONTEND:latest
                '''
            }
        }

        stage('Push Images') {
            steps {
                sh '''
                docker push $ECR_BACKEND:latest
                docker push $ECR_FRONTEND:latest
                '''
            }
        }
    }
}

stage('Deploy to EC2') {
    steps {
        sh '''
        ssh -o StrictHostKeyChecking=no ubuntu@<EC2_PUBLIC_IP> "
        
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 740349584703.dkr.ecr.ap-south-1.amazonaws.com
        
        docker pull 740349584703.dkr.ecr.ap-south-1.amazonaws.com/redbus-backend:latest
        docker pull 740349584703.dkr.ecr.ap-south-1.amazonaws.com/redbus-frontend:latest
        
        docker stop backend || true
        docker rm backend || true
        docker stop frontend || true
        docker rm frontend || true
        
        docker run -d -p 5000:5000 --name backend redbus-backend:latest
        docker run -d -p 3000:3000 --name frontend redbus-frontend:latest
        
        "
        '''
    }
}
