apiVersion: v1
kind: Service
metadata:
  name: redbus-frontend
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: redbus-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
