apiVersion: v1
kind: Secret
metadata:
  name: redbus-secrets
  namespace: default
type: Opaque
stringData:
  # MongoDB Atlas connection string
  DATABASE: "mongodb+srv://redbus_db_user_1:umJkhSujb8dZoc2a@redbuscnstructweek.bujg6.mongodb.net/redbus?retryWrites=true&w=majority"
  # Stripe API Secret key (Add your live key here if needed)
  STRIPE_SECRET_KEY: "sk_test_51IQA1eGqKz0k8..."
